server:
  port: 8079
  grpc:
    port: 79

spring:
  application:
    name: support-service
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 8MB # файлы + поля
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8084}/realms/${KEYCLOAK_REALM:my_realm}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB_NAME:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:igor333333}
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  threads:
    virtual:
      enabled: true

  main:
    keep-alive: true # не хавершит приложение,если все активные потоки - виртуальные

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: support-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"  #десериализация любых объектов
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max:
          request:
            size: 8_388_608
        buffer:
          memory: 67_728_640 # размер буффера
      compression-type: snappy #сжатие

support_agent:
  email: someEmail@mail.ru

eureka:
  client:
     service-url:
      defaultZone:
        http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

  instance:
    metadata-map:
      grpc-port: ${server.grpc.port}