server:
  port: 8087

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-api

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/users, /api/users/**
          filters:
            - name: JwtCookieAuthFilter


        - id: support
          uri: lb://support-service
          predicates:
            - Path=/api/support, /api/support/**
          filters:
            - name: JwtCookieAuthFilter

        - id: websocket-support
          uri: lb://support-service
          predicates:
          - Path=/ws-support/**
          filters:
            - name: JwtCookieAuthFilter

        - id: media
          uri: lb://media-service
          predicates:
            - Path=/api/media, /api/media/**
          filters:
            - name: JwtCookieAuthFilter



        - id: catalogue
          uri: lb://catalogue-service
          predicates:
            - Path=/api/catalogue, /api/catalogue/**
          filters:
            - name: JwtCookieAuthFilter



        - id: cart
          uri: lb://cart-wishlist-service
          predicates:
            - Path=/api/cart, /api/cart/**
          filters:
            - name: JwtCookieAuthFilter



        - id: wishlist
          uri: lb://cart-wishlist-service
          predicates:
            - Path=/api/wish-list, /api/wish-list/**
          filters:
            - name: JwtCookieAuthFilter

        - id: review
          uri: lb://review-service
          predicates:
            - Path=/api/review, /api/review/**
          filters:
            - name: JwtCookieAuthFilter


        - id: frontend-static
          uri: lb://frontend-service
          predicates:
            - Path=/static/**, /*.css, /*.js, /*.ico, /*.png, /*.jpg, /*.svg, /*.woff2


        - id: frontend-templates
          uri: lb://frontend-service
          predicates:
              - Path=/**
          filters:
            - name: JwtCookieAuthFilter


eureka:
  client:
    service-url:
      defaultZone:
        http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

