

services:
  redis:
    restart: unless-stopped
    image: redis
    container_name: my_redis
    ports:
      - "56379:6379"
    volumes:
      - ./config/redis/import:/data

  keycloak:
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: my_keycloak
    command:
      - start-dev
      - --import-realm
    ports:
      - "58084:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./config/keycloak/import:/opt/keycloak/data/import

  postgres:
      restart: unless-stopped
      image: postgres:latest
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5433:5432"
      volumes:
        - ./config/postgres/import:/var/lib/postgresql/18/main

  minio:
    restart: unless-stopped
    image: minio/minio
    ports:
      - "59000:9000"   # Web API
      - "59001:9001"   # Web UI
    volumes:
      - ./config/minIO/import:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

  zookeeper:
    restart: unless-stopped
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "52181:2181"

  kafka:
    restart: unless-stopped
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "59092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 10_485_760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 12_582_912

  eureka:
    restart: unless-stopped
    build:
      context: .
      dockerfile: eureka/Dockerfile

    image: eureka:latest
    ports:
      - "58761:8761"

  gateway:
    restart: unless-stopped
    build:
      context: .
      dockerfile: gateway/Dockerfile

    image: gateway:latest
    ports:
      - "58087:8087"
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
    depends_on:
      - eureka


  cart-wishlist-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: cart-wishlist-service/Dockerfile
    image: cart-wishlist-service:latest
    ports:
      - "58080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB}
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=my_realm
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    depends_on:
      - postgres
      - keycloak
      - eureka


  catalogue-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: catalogue-service/Dockerfile
    image: catalogue-service:latest
    ports:
      - "58082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB}
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=my_realm
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092

    depends_on:
      - postgres
      - keycloak
      - kafka
      - eureka
      - media-service


  email-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: email-service/Dockerfile
    image: email-service:latest
    ports:
      - "58081:8081"
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=my_realm
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_ADDRESS=${MAIL_ADDRESS}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

    depends_on:
      - keycloak
      - kafka
      - eureka


  frontend-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: frontend-service/Dockerfile
    image: frontend-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=my_realm

    depends_on:
      - keycloak
      - eureka


  media-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: media-service/Dockerfile
    image: media-service:latest
    ports:
      - "58078:8078"
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=my_realm
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    depends_on:
      - keycloak
      - kafka
      - minio
      - redis
      - eureka




  order-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: order-service/Dockerfile
    image: order-service:latest
    ports:
      - "58090:8090"
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=my_realm
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB}
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - GEOAPIFY_TOKEN=${GEOAPIFY_TOKEN}
    depends_on:
      - kafka
      - keycloak
      - postgres
      - eureka


  review-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: review-service/Dockerfile
    image: review-service:latest
    ports:
      - "58089:8089"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=my_realm
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB}
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
    depends_on:
      - redis
      - keycloak
      - postgres
      - kafka
      - eureka


  support-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: support-service/Dockerfile
    image: support-service:latest
    ports:
      - "58079:8079"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB}
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=my_realm
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    depends_on:
      - postgres
      - keycloak
      - kafka
      - eureka



  user-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: user-service:latest
    ports:
      - "58077:8077"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_NAME=${POSTGRES_DB}
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=my_realm
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - keycloak
      - kafka
      - redis
      - eureka






