server:
  port: 8077
  grpc:
    port: 77

spring:
  application:
    name: user-service
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 8MB # файлы + поля

  security:
     oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8084}/realms/${KEYCLOAK_REALM:my_realm}

      client:
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8084}/realms/${KEYCLOAK_REALM:my_realm}
            user-name-attribute: preferred_username

        registration:
          keycloak:
            client-id: user_service
            client-secret: ${KEYCLOAK_CLIENT_SECRET:mzcN7w1k7cTM0pBO0FgT4tBhNIPNn0hc}
            scope:
              - openid
              - microprofile-jwt

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB_NAME:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:igor333333}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"  #десериализация любых объектов
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max:
          request:
            size: 8_388_608
        buffer:
          memory: 67_728_640 # размер буффера
      compression-type: snappy #сжатие



eureka:
  client:
    service-url:
      defaultZone:
        http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

  instance:
    metadata-map:
      grpc-port: ${server.grpc.port}
