server:
  port: 8078
  grpc:
    port: 78

spring:
  application:
    name: media-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8084}/realms/${KEYCLOAK_REALM:my_realm}
  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"  #десериализация любых объектов
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


minio:
  url: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}

eureka:
   client:
     service-url:
      defaultZone:
        http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
   instance:
     metadata-map:
       grpc-port: ${server.grpc.port}