server:
  port: 8081
spring:
  application:
    name: email_service
  mail:
    host: ${MAIL_HOST:smtp.mail.ru}
    port: ${MAIL_PORT:465}
    username: ${MAIL_ADDRESS:tempmailfom@mail.ru}
    password: ${MAIL_PASSWORD:LXOLtuFoq91qHkNGePmk}
    protocol: ${MAIL_PROTOCOL:smtps}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    default-encoding: UTF-8

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8084}/realms/${KEYCLOAK_REALM:my_realm}

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: email-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"  #десериализация любых объектов


  threads:
    virtual:
      enabled: true

  main:
    keep-alive: true

eureka:
  client:
    service-url:
      defaultZone:
        http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/