server:
  port: 8083
spring:
  application:
    name: frontend-service
  flyway:
    enabled: false
  threads:
   virtual:
     enabled: true
  main:
   keep-alive: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8084}/realms/${KEYCLOAK_REALM:my_realm}
eureka:
  client:
    service-url:
      defaultZone:
        http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
