server:
  port: 8083
spring:
  mail:
    host: smtp.mail.ru
    port: 465
    username: tempmailfom@mail.ru
    password: LXOLtuFoq91qHkNGePmk
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    default-encoding: UTF-8
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: igor333333
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
       provider:
          keycloak:

            issuer-uri: http://localhost:8084/realms/my_realm
            user-name-attribute: preferred_username

       registration:
         keycloak:
           client-id: manager_app
           client-secret: jgzYnUEgRkbZan2ly9Jhh8oixe5DRgSe
           scope:
             - openid
             - microprofile-jwt
             - view_catalogue
             - edit_catalogue




  data:
    redis:
      host: localhost
      port: 6379





my_shop:
  support_agent:
    email: gimmycool444e@mail.ru
  services:
    catalogue:
      uri: http://localhost:8082
      registration-id: keycloak

keycloak:
  server-uri: http://localhost:8084
  realm: "my_realm"

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin